version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
      - mv target/lavagna-jetty-console.war terraform/Build/ROOT.war
      - cd terraform/Build/
artifacts:
  files:
    - ROOT.war
