version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
      - mv target/lavagna-jetty-console.war terraform/Build/ROOT.war
artifacts:
  files:
    - terraform/Build/ROOT.war
