version: '3.8'

services:
  postgresql:
    image: 10.26.0.176:5000/postgres:9.4
    restart: always
    environment:
      POSTGRES_DB: lavagna
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lavagna

  app-deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
      args:
        DB_DIALECT: PGSQL
        DB_URL: jdbc:postgresql://postgresql:5432/lavagna
        DB_USERNAME: myuser
        DB_PASSWORD: mypassword
        SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    networks:
      - lavagna

volumes:
  postgres-data:
    driver: local

networks:
  lavagna:
    driver: bridge