FROM maven:3.8.6-openjdk-8

WORKDIR /app

COPY . /app

RUN set -e && mvn package -DskipTests

EXPOSE 8080

WORKDIR /app/target

CMD ["sh", "-c", "java -Ddatasource.dialect=$DB_DIALECT -Ddatasource.url=$DB_URL -Ddatasource.username=$DB_USERNAME -Ddatasource.password=$DB_PASSWORD -Dspring.profile.active=$SPRING_PROFILES_ACTIVE -jar lavagna-jetty-console.war"]