version: '3.8'

services:
  postgresql:
    container_name: lavagna-db
    image: 10.26.0.176:5000/postgres:9.4
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-datadog-db.conf.sql:/docker-entrypoint-initdb.d/postgres-datadog-db.conf.sql
    networks:
      - lavagna

  app:
    container_name: lavagna-app
    build:
      context: .
      dockerfile: Dockerfile.deploy
      args:
        DB_DIALECT: ${DB_DIALECT}
        DB_URL: "${DB_URL}"
        DB_USERNAME: "${DB_USER} "
        DB_PASSWORD: "${DB_PASSWORD}"
        SPRING_PROFILES_ACTIVE: "dev"
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    networks:
      - lavagna

  datadog-agent:
    build:
      context: .
      dockerfile: Dockerfile.datadog.yml
      args:
        POSTGRES_HOST: postgresql
        POSTGRES_PORT: "5432"
        POSTGRES_USER: "datadog"
        POSTGRES_PASSWORD: "datadog"
    environment:
      DD_API_KEY: "${DATADOG_API_KEY}"
      DD_SITE: "${DATADOG_SITE}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    depends_on:
      - app
    networks:
      - lavagna

    datadog:
      image: datadog/agent:latest
      environment:
        DD_API_KEY: "${DATADOG_API_KEY}"
        DD_SITE: "${DATADOG_SITE}"
        DD_LOGS_ENABLED: "true"
        DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
        DD_APM_ENABLED: "true"
        DD_PROCESS_AGENT_ENABLED: "true"
        DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
        # PostgreSQL integration settings
        DD_PGSQL_HOST: "lavagna-db"
        DD_PGSQL_PORT: 5432
        DD_PGSQL_USER: "datadog"
        DD_PGSQL_PASS: "datadog"
        DD_PGSQL_DBNAME: "${DB_NAME}"
        DD_PGSQL_MAX_CONNECTIONS: "5"
        DD_PGSQL_MAX_CUSTOM_QUERIES: "5"
        DD_PGSQL_MIN_COLLECTION_INTERVAL: "10"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      depends_on:
        - postgres
      networks:
        - datadog_network

volumes:
  postgres-data:
    driver: local

networks:
  lavagna:
    driver: bridge