version: '3'

services:
  postgresql:
    image: 10.26.0.176:5000/postgres:9.4
    environment:
      POSTGRES_DB: lavagna
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - lavagna

  mysql:
    image: 10.26.0.176:5000/mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: lavagna
      MYSQL_PASSWORD: password
    networks:
      - lavagna

  mariadb:
    image: 10.26.0.176:5000/mariadb:10.1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: lavagna
      MYSQL_PASSWORD: password
    networks:
      - lavagna

networks:
  lavagna:
    driver: bridge

