version: '3'

services:
  postgresql:
    image: postgres:9.4
    environment:
      POSTGRES_DB: lavagna
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - lavagna

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: lavagna
      MYSQL_PASSWORD: password
    networks:
      - lavagna

  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: lavagna
      MYSQL_PASSWORD: password
    networks:
      - lavagna


networks:
  lavagna:
    driver: bridge

