FROM ubuntu:latest
# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install -y maven openjdk-8-jdk

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

WORKDIR /app

COPY . /app

RUN set -e && mvn package -DskipTests