FROM maven:3.8.6-openjdk-8 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src src
RUN mvn package -DskipTests


FROM openjdk:8-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/lavagna-jetty-console.war lavagna-jetty-console.war