apiVersion: v1
kind: Pod
metadata:
  name: dockercontainer
  namespace: jenkins
spec:
  containers:
  - image: docker:24.0.0-rc.1-dind
    name: docker
    securityContext:
      privileged: true
    args:
    - dockerd
    - --insecure-registry=your-registry-domain.com:5000