apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: jenkins
spec:
  containers:
  - image: localhost:5000/lavagna-build:latest
    name: test
    tty: true
    resources:
      requests:
        cpu: "500m"
      limits:
        cpu: "1000m"