apiVersion: v1
kind: Pod
metadata:
  name: dockercontainer
  namespace: jenkins
spec:
  containers:
  - image: docker:24.0.0-rc.1-dind
    name: docker-builder
    securityContext:  
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: "/certs"
    command: ["/bin/sh"]
    args: ["-c", "dockerd-entrypoint.sh --insecure-registry=docker-registry:5000"]
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket-volume
  - image: dtzar/helm-kubectl:latest
    name: kubectl-deploy
    tty: true
  volumes:
  - name: docker-socket-volume
    hostPath:
      path: /var/run/docker.sock
      type: File