apiVersion: v1
kind: Pod
metadata:
  name: dockercontainer
  namespace: default
spec:
  containers:
  - image: docker:24.0.0-rc.1-dind
    name: docker
    securityContext:
      privileged: true # this should do the trick