apiVersion: v1
kind: Pod
metadata:
  name: dockercontainer
  namespace: jenkins
spec:
  containers:
  - image: docker:24.0.0-rc.1-dind
    name: docker
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-daemon-config
      mountPath: /etc/docker/daemon.json
      subPath: daemon.json
  volumes:
  - name: docker-daemon-config
    configMap:
      name: docker-daemon-config