apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: jenkins
spec:
  containers:
  - image: localhost:5000/lavagna-build:latest
    name: pod-test
    tty: true
  - image: mysql:latest
    name: mysql
    env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "yes"
    - name: MYSQL_DATABASE
      value: "lavagna"
    - name: MYSQL_PASSWORD
      value: "password"