apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: jenkins
spec:
  containers:
  - image: localhost:5000/lavagna-build:latest
    name: pod-test
    tty: true
  - image: postgres:9.4
    name: db
    env:
    - name: POSTGRES_DB
      value: "lavagna"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "password"