apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: 8080
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 10.26.0.176:5000/lavagna-build:20
          env:
            - name: DB_DIALECT
              value: PGSQL
            - name: DB_URL
              value: "${DB_URL}"
            - name: DB_USERNAME
              value: "${DB_USER}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          ports:
            - containerPort: 8080
