apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-main
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-qa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


/nfs/kubedata 192.168.49.2(rw,sync,no_root_squash,no_subtree_check)
