apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: my-nginx
