apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: "{{ (.Values.app).name}}-deployment"
type: Opaque
data:
  username: {{ .Values.db.username | b64enc | quote }}
  password: {{ .Values.db.password | b64enc | quote }}
